CREATE DATABASE Exercicio_1_3;

USE Exercicio_1_3;

CREATE TABLE Cliente(
	IdCliente INT PRIMARY KEY IDENTITY,
	NomeCliente VARCHAR(50) NOT NULL
);

CREATE TABLE Clinica(
	IdClinica INT PRIMARY KEY IDENTITY,
	NomeClinica VARCHAR(20) NOT NULL
);

CREATE TABLE TipoPet(
	IdTipoPet INT PRIMARY KEY IDENTITY,
	NomeTipoPet VARCHAR(25) NOT NULL
);

CREATE TABLE RacaPet(
	IdRacaPet INT PRIMARY KEY IDENTITY,
	IdTipoPet INT FOREIGN KEY REFERENCES TipoPet(IdTipoPet) NOT NULL,
	NomeRacaPet VARCHAR(25) NOT NULL
);



SELECT * FROM Cliente;
SELECT * FROM Clinica;
SELECT * FROM TipoPet;
SELECT * FROM RacaPet;